sitebinomotron/binomotron/urls.py
from django.urls import path

from . import views

app_name = 'binomotron'

urlpatterns = [

    path('', views.index, name='index'),

    path('apprenant/', views.apprenantview, name='apprenant'),
    path('apprenant/add/', views.ApprenantAddClass.as_view(), name = 'apprenant_add'),
    path('apprenant/edit/<int:pk>/', views.ApprenantEditClass.as_view(), name = 'apprenant_edit'),
    path('apprenant/<int:pk>/', views.ApprenantDetailView.as_view(), name='apprenant_detail'),
    path('apprenant/supprimer/<int:pk>/', views.ApprenantDeleteView.as_view(), name="supprimer-apprenant"),

    path('brief/', views.briefview, name='brief'),
    path('brief/add/', views.BriefAddClass.as_view(), name = 'brief_add'),
    path('brief/edit/<int:pk>/', views.BriefEditClass.as_view(), name = 'brief_edit'),
    path('brief/<int:pk>/', views.BriefDetailView.as_view(), name='brief_detail'),
    path('brief/supprimer/<int:pk>/', views.BriefDeleteView.as_view(), name="supprimer-brief"),

    path('groupe/create/<int:pk>', views.groupecreate , name ='groupe_create'),

]

sitebinomotron/sitebinomotron/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('binomotron.urls')),
    path('admin/', admin.site.urls),
]

sitebinomotron/binomotron/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, ValidationError
from django.utils.translation import gettext_lazy as _


# Modèle django pour la Table SQl Apprenant
class Apprenant(models.Model):
    nom = models.CharField(max_length=200, null=True)
    prenom = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f"{self.nom} {self.prenom}"

# Valide la date de début si pas antérieure à la date du jour
def validate_datedebut(value):
    if value < datetime.date.today():
        raise ValidationError(
            _("La date de début ne peut pas être dans le passé"),
            params={'value': value},
        )

# Modèle django pour la Table SQl Brief
class Brief(models.Model):
    nom = models.CharField(max_length=200, null=True)
    lien = models.URLField(max_length=200, unique=True)
    # Pour la taille des n-omes on accepte que des valeurs supérieurs ou égales à 2 
    nombre = models.PositiveIntegerField(default=2, validators = [MinValueValidator(2)])
    # Indique la date de début et de fin d'un brief 
    date_debut = models.DateField(default=timezone.now, validators = [validate_datedebut])
    # date_debut = models.DateField(default=timezone.now)
    date_fin = models.DateField(default=timezone.now)

    # Si la date de fin est antérieure à la date de début, raise ValidationError
    def clean(self):      
       
        if self.date_fin < self.date_debut:
            raise ValidationError("La date de fin ne peut pas être antérieure à la date de début")

    def __str__(self):
        return f"{self.nom}, groupes de {self.nombre} personnes"
    
# Modèle django pour la Table SQl Groupe
class Groupe(models.Model):
    nom = models.CharField(max_length=200, null=True)
    # Entre Brief et Groupe il y a une relation de 1 to many et on décide d'indiquer cette relation dans le modèle Groupe
    brief = models.ForeignKey(Brief, on_delete=models.CASCADE)
    # Entre Apprenant et Groupe, il y a une relation de many to many et on décide d'indiquer cette relation dans Groupe
    apprenants = models.ManyToManyField(Apprenant)


    def __str__(self):
        return f"{self.nom},brief {self.brief}"

sitebinomotron/binomotron/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from .group_crea import groupe_create

from .models import Apprenant, Brief, Groupe

# View pour la page d'accueil de l'API
def index(request) :
    return render(request, 'other/index.html')

# Partie Apprenant

# View pour la page des apprenants
def apprenantview(request) :
    # On affiche la liste des apprenants trier par le nom
    if request.method == 'GET' :
        apprenant_list = Apprenant.objects.all().order_by('nom')
        return render(request, 'apprenant/apprenant.html', {'apprenant_list' : apprenant_list})
    # Lorsque l'on effectue une recherche il s'agit d'une méthod post et on affiche les apprenants dont le nom
    # contient le motif de recherche
    elif request.method ==  'POST' :
        apprenant_list = Apprenant.objects.all().filter(nom__icontains=request.POST.get('search'))
        return render(request, 'apprenant/apprenant.html', {'apprenant_list' : apprenant_list})

# View pour le formulaire afin d'ajouter un apprenant
class ApprenantAddClass(SuccessMessageMixin, CreateView):
    model = Apprenant
    template_name = "apprenant/apprenant_add.html"
    fields = ['nom', 'prenom']
    
    # On retourne un message de succès et une création d'un apprenant réussie retourne sur la page affichant
    # la liste des apprenants
    success_message = "%(prenom)s %(nom)s ajouté avec succès!"
    def get_success_url(self, **kwargs):
        return reverse_lazy('binomotron:apprenant')

# View pour la modification des informations pour un apprenant
class ApprenantEditClass(SuccessMessageMixin, UpdateView):
    model = Apprenant
    fields = ['nom', 'prenom']
    template_name = "apprenant/apprenant_edit.html"
    
    # On retourne un message de succès et une modification d'un apprenant réussie retourne sur la page affichant
    # la liste des apprenants
    success_message = "%(prenom)s %(nom)s modifié avec succès!"
    def get_success_url(self, **kwargs):
        return reverse_lazy('binomotron:apprenant')

# View affichant les détails d'un apprenant
class ApprenantDetailView(generic.DetailView):
    model = Apprenant
    template_name = 'apprenant/apprenant_detail.html'

# View pour demander la confirmation de suppression d'un apprennant
class ApprenantDeleteView(SuccessMessageMixin, DeleteView):
    model = Apprenant
     
    # url de redirection et message de succès
    success_url ="/apprenant"
    success_message = "Éliminé avec succès! AU SUIVANT!!!" 
    template_name = "apprenant/apprenant_deleteconfirmation.html"


# Partie Brief

# View pour la page des briefs
def briefview(request) :
    # On affiche la liste des briefs trier par le nom
    if request.method == 'GET' :
        brief_list = Brief.objects.all().order_by('nom')
        return render(request, 'brief/brief.html', {'brief_list' : brief_list})
    # Lorsque l'on effectue une recherche il s'agit d'une méthod post et on affiche les briefs dont le nom
    # contient le motif de recherche
    elif request.method ==  'POST' :
        brief_list = Brief.objects.all().filter(nom__icontains=request.POST.get('search'))
        return render(request, 'brief/brief.html', {'brief_list' : brief_list})

# View pour le formulaire afin d'ajouter un brief
class BriefAddClass(SuccessMessageMixin, CreateView):
    model = Brief
    template_name = "brief/brief_add.html"
    # Sur la date de début et de fin on a un validateur pour bloquer la création d'un brief ayant des dates
    # antérieurs à la date du jour de création du brief
    # De plus la date de fin ne peut pas être antérieur à la date de début
    fields = ['nom', 'lien', 'nombre', 'date_debut', 'date_fin']
    
    # On retourne un message de succès et une création d'un brief réussie retourne sur la page affichant
    # la liste des briefs
    success_message = "%(nom)s ajouté avec succès!"
    def get_success_url(self, **kwargs):
        return reverse_lazy('binomotron:brief')

# View pour la modification des informations pour un brief
class BriefEditClass(SuccessMessageMixin, UpdateView):
    model = Brief
    
    # On affiche seulement les champs nom, lien et nombre car le validateur sur les dates 
    # bloque l'envoie du formulaire si les dates sont antérieurs à la date du jour
    fields = ['nom', 'lien', 'nombre']
    # fields = ['nom', 'lien', 'nombre', 'date_debut', 'date_fin']
    template_name = "brief/brief_edit.html"
    
    # On retourne un message de succès et une modification d'un brief réussie retourne sur la page affichant
    # la liste des briefs
    success_message = "%(nom)s modifié avec succès!"
    def get_success_url(self, **kwargs):
        return reverse_lazy('binomotron:brief')

    # On récupère et enregistre le nombre pour la taille des groupes d'apprenants avant qu'il soit modifié
    def get_context_data(self, **kwargs):
        pk = self.get_object()
        context = super().get_context_data(**kwargs)
        brief = Brief.objects.get(pk = pk.pk)

        context['ancien_nombre'] = brief.nombre
        return context
    
    # Si la taille des groupes d'apprenants est modifié (en comparant au nombre sauvegardé juste avant)
    # on supprime l'ensemble des groupes liés au brief modifié
    def post(self, request, *args: str, **kwargs):
        form_nb_appr = request.POST["ancien_nombre"]
        current_brief = self.get_object()
        previous_nombre = current_brief.nombre
        if previous_nombre != form_nb_appr:
            Groupe.objects.filter(brief = current_brief.pk).delete()

        return super().post(request, *args, **kwargs)

# View affichant les détails d'un brief
class BriefDetailView(generic.DetailView):
    model = Brief
    template_name = 'brief/brief_detail.html'
    
    # On récupère les groupes liés au brief sélectionné et on stocke ces listes de groupes d'apprenants
    # dans le contexte pour être utilisable dans la page html
    def get_context_data(self, **kwargs) :
        pk = self.get_object()
        context = super().get_context_data(**kwargs)
        groups = Groupe.objects.filter(brief = pk)
                
        group_list = {}

        for group in groups :
            student = group.apprenants.select_related()
            group_list[group.nom] =student
        context['group_list'] = group_list
        return context

# View pour demander la confirmation de suppression d'un brief
class BriefDeleteView(SuccessMessageMixin, DeleteView):
    model = Brief
     
    # url de redirection
    success_url ="/brief"
    success_message = "Éliminé avec succès! AU SUIVANT!!!" 
    template_name = "brief/brief_deleteconfirmation.html"

# Partie Groupe

# On appel la fonction qui crée les groupes et on redirige la vue directement sur la page du brief 
# dont on vient de créer les groupes
def groupecreate(request, pk) :
    groupe_create(pk)
    return HttpResponseRedirect(reverse('binomotron:brief_detail', args=[pk]))

sitebinomotron/binomotron/templates/brief/brief.html
<!DOCTYPE html>
<html lang="en-US">
  {% load static %}
  <link rel="stylesheet" href="{% static 'binomotron/style.css' %}">
  <head>
    <meta charset="utf-8" />
    <title>Binomotron, liste des briefs</title>
  </head>
  <body>
    <header>
      <a href="{% url 'binomotron:index' %}">Accueil</a>
    </header>
    <p>Liste des briefs</p>
    <form action=" {% url 'binomotron:brief'%}" method="post">
      {% csrf_token %}
      <input type="search" pattern="[a-zA-Z]{1,200}" placeholder="nom" name="search">
      <button type="submit">Recherche</button>
    </form>
    <form><button class='add-btn' formaction="{% url 'binomotron:brief_add' %}">Ajouter</button></form>
    {% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
  {% endif %}

    {% if brief_list %}
      <ul>
      {% for brief in brief_list %}
        <li>
          <form >
            {% csrf_token %}
            <a href="{% url 'binomotron:brief_detail' brief.id %}">{{ brief.nom }}</a>
            <button class ='modif-btn' formaction="{% url 'binomotron:brief_edit' brief.id %}">Modifier</button>
            <button class = "delete-btn" formaction="{% url 'binomotron:supprimer-brief' brief.id%}">Supprimer</button>
          </form>
        </li>
      {% endfor %}
      </ul>
      {% else %}
        <p>Pas de briefs disponibles</p>
      {% endif %}
  </body>
</html>

sitebinomotron/binomotron/templates/brief/brief_add.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Formulaire de création d'un brief</title>
    {% load static %}
    <!-- <link rel="stylesheet" href="{% static '/style.css' %}"> -->
  </head>
  <body>
    <header>
      <a href="{% url 'binomotron:brief' %}">Brief</a>
    </header>
    <h1>Nouveau brief</h1>
    {% block content %}
      {% if form %}
        {% for field in form %}
         {{ field.errors }}
        {% endfor %}
      {% endif %}
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Ajouter">
      </form>
    {% endblock content %}
  </body>
</html>

sitebinomotron/binomotron/templates/brief/brief_deleteconfirmation.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Formulaire pour ajouter un apprenant</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'binomotron/style.css' %}">
  </head>
  <body>
    <form method="post">{% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer "{{ object }} "?</p>
        <input class = "back-btn" type="button" value="Annuler" onclick="history.back()"> 
        <input class = "confirm-btn" type="submit" value="Confirmer">
    </form>
  </body>
</html>

sitebinomotron/binomotron/templates/brief/brief_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Formulaire pour ajouter un apprenant</title>
        {% load static %}
        <!-- <link rel="stylesheet" href="{% static '/style.css' %}"> -->
    </head>
    <body>
        <header>
            <a href="{% url 'binomotron:brief' %}">Brief</a>
        </header>
        <h1>{{brief.nom}} </h1>
        <p> Lien vers le brief : {{brief.lien}} </p>
        <p> Date de début du projet : {{brief.date_debut}} </br>
            Date limite de rendu : {{brief.date_fin}} </p>

        {% if group_list %}
            <ul>
            {% for gname, students in group_list.items %}
            <li>
                <p>{{gname}}</p>
                {% for student in students %}
                <ul>
                    <li>
                        <p>{{student.prenom}} {{student.nom}}</p>
                    </li>
                </ul>
                {% endfor %}   
            </li>
            {% endfor %}
            </ul>
            {% else %}
            <p>Les groupes n'ont pas encore été créés pour le brief {{brief.nom}}</p>
            <form>
                {% csrf_token %}
                <button class ='create-btn' formaction="{% url 'binomotron:groupe_create' brief.id %}">Créer les groupes</button>
            </form>
            {% endif %}
    </body>
</html>

sitebinomotron/binomotron/templates/brief/brief_edit.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Formulaire de modification d'un brief</title>
    {% load static %}
    <!-- <link rel="stylesheet" href="{% static '/style.css' %}"> -->
  </head>
  <body>
    <header>
      <a href="{% url 'binomotron:brief' %}">Brief</a>
    </header>
    <h1>Modification d'un brief</h1>
    {% block content %}
      {% if form %}
        {% for field in form %}
         {{ field.errors }}
        {% endfor %}
      {% endif %}
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="hidden" name="ancien_nombre" value="{{ ancien_nombre }}">
        <input type="submit" value="Valider">
      </form>
    {% endblock content %}
  </body>
</html>